"""Static webdir monitor publisher for Purohit rerun projects.

This module writes a PESummary-style static monitor into a web-accessible
``public_html``/webdir directory. It does not expose a live web server.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import platform
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from typing import Any

import yaml

try:
    import psutil
except ImportError:  # pragma: no cover - optional dependency
    psutil = None


CONDOR_STATUS = {1: "idle", 2: "running", 3: "completed", 4: "removed", 5: "held", 6: "suspended"}
CONDOR_ATTRIBUTES = ",".join([
    "ClusterId", "ProcId", "JobStatus", "RequestCpus", "RequestMemory", "RemoteHost",
    "RemoteWallClockTime", "JobCurrentStartDate", "EnteredCurrentStatus", "HoldReason",
    "DiskUsage", "ImageSize", "ResidentSetSize", "MemoryUsage",
])
DEFAULT_OUTPUT_EXTENSIONS = (".png", ".jpg", ".jpeg", ".svg", ".pdf", ".html", ".txt", ".log", ".out", ".err", ".hdf5", ".json")

INDEX_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Purohit static job manager</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif; margin: 2rem; line-height: 1.35; }
    h1, h2 { margin-bottom: 0.4rem; }
    .muted { opacity: 0.72; }
    .card { border: 1px solid rgba(128,128,128,0.25); border-radius: 12px; padding: 1rem; margin: 1rem 0; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; }
    th, td { text-align: left; border-bottom: 1px solid rgba(128,128,128,0.25); padding: 0.55rem; font-size: 0.9rem; vertical-align: top; }
    th { position: sticky; top: 0; background: Canvas; }
    code, pre { padding: 0.1rem 0.25rem; border-radius: 4px; background: rgba(128,128,128,0.15); }
    pre { white-space: pre-wrap; padding: 0.75rem; overflow-x: auto; }
    a { text-decoration: none; }
    .status-running { color: #047857; font-weight: 700; }
    .status-completed { color: #2563eb; font-weight: 700; }
    .status-held, .status-removed, .status-failed { color: #b91c1c; font-weight: 700; }
    .status-idle, .status-submitted, .status-pending { color: #92400e; font-weight: 700; }
    .small { font-size: 0.82rem; }
    .links a { display: block; margin-bottom: 0.2rem; }
  </style>
</head>
<body>
  <h1>Purohit static job manager</h1>
  <p class="muted">PESummary-style static view generated by a background publisher/manager. This page reads static JSON only.</p>

  <div class="card">
    <div><strong>Project:</strong> <code id="project-dir">loading...</code></div>
    <div><strong>Generated:</strong> <span id="generated">loading...</span></div>
    <div><strong>Publisher host:</strong> <span id="publisher-host">loading...</span></div>
    <div><strong>Command file:</strong> <code id="command-file">not configured</code></div>
  </div>

  <h2>Publisher host resources</h2>
  <div id="system" class="grid"></div>

  <h2>Jobs</h2>
  <div class="card">
    <table>
      <thead>
        <tr>
          <th>Event</th><th>Status</th><th>Cluster ID</th><th>CPUs</th><th>Memory MB</th>
          <th>Remote host / node</th><th>Runtime</th><th>Disk / RSS</th><th>Outputs</th><th>Heartbeat</th><th>Notes</th>
        </tr>
      </thead>
      <tbody id="jobs"></tbody>
    </table>
  </div>

  <h2>Command queue</h2>
  <div class="card">
    <p class="muted small">Static pages cannot write to the submit host by themselves. To manage jobs, write commands into the manager command JSON file on the submit host, or use <code>scripts/write_manager_command.py</code>. Supported actions: <code>submit_event</code>, <code>hold_event</code>, <code>release_event</code>, <code>remove_event</code>, <code>refresh</code>.</p>
    <pre id="command-example">loading...</pre>
  </div>

<script>
function fmt(value) { return value === null || value === undefined || value === "" ? "—" : value; }
function card(label, value) { return `<div class="card"><div class="muted small">${label}</div><div><strong>${fmt(value)}</strong></div></div>`; }
function statusClass(status) { return `status-${String(status || "unknown").toLowerCase()}`; }
function heartbeatText(hb) {
  if (!hb) return "—";
  const bits = [];
  if (hb.hostname) bits.push(hb.hostname);
  if (hb.load_avg_1m !== undefined && hb.load_avg_1m !== null) bits.push(`load1=${hb.load_avg_1m}`);
  if (hb.memory_available_gb !== undefined && hb.memory_available_gb !== null) bits.push(`mem_avail=${hb.memory_available_gb} GB`);
  if (hb.age_seconds !== undefined && hb.age_seconds !== null) bits.push(`age=${Math.round(hb.age_seconds)}s`);
  return bits.join("; ") || "—";
}
function outputLinks(outputs) {
  if (!outputs || outputs.length === 0) return "—";
  return `<div class="links">${outputs.map(item => `<a href="${item.href}">${item.label}</a>`).join("")}</div>`;
}
function commandExample(event) {
  return JSON.stringify({commands: [
    {action: "submit_event", event: event || "S240000a"},
    {action: "hold_event", event: event || "S240000a"},
    {action: "release_event", event: event || "S240000a"}
  ]}, null, 2);
}
async function refresh() {
  const response = await fetch(`status.json?ts=${Date.now()}`, {cache: "no-store"});
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const data = await response.json();
  document.getElementById("project-dir").textContent = data.project_dir;
  document.getElementById("generated").textContent = new Date(data.generated_at * 1000).toLocaleString();
  document.getElementById("publisher-host").textContent = data.system.hostname || "—";
  document.getElementById("command-file").textContent = data.command_file || "not configured";
  const s = data.system || {};
  document.getElementById("system").innerHTML = [
    card("Host", s.hostname), card("Platform", s.platform), card("Logical CPUs", s.cpu_count_logical),
    card("Physical CPUs", s.cpu_count_physical), card("CPU frequency MHz", s.cpu_freq_mhz_current),
    card("Load average 1m", s.load_avg_1m), card("Load %", s.load_percent_1m), card("Memory used %", s.memory_used_percent),
  ].join("");
  const rows = (data.jobs || []).map(job => `<tr>
      <td>${fmt(job.event)}</td><td class="${statusClass(job.status)}">${fmt(job.status)}</td><td>${fmt(job.jobid)}</td>
      <td>${fmt(job.request_cpus)}</td><td>${fmt(job.request_memory_mb)}</td><td>${fmt(job.remote_host)}</td>
      <td>${fmt(job.runtime)}</td><td>${fmt(job.disk_usage)} / ${fmt(job.rss_kb)}</td><td>${outputLinks(job.outputs)}</td>
      <td class="small">${heartbeatText(job.heartbeat)}</td><td class="small">${fmt(job.note)}</td>
    </tr>`).join("");
  document.getElementById("jobs").innerHTML = rows || `<tr><td colspan="11">No jobs found.</td></tr>`;
  document.getElementById("command-example").textContent = commandExample((data.jobs || [])[0]?.event);
}
refresh().catch(err => { document.getElementById("generated").textContent = `error: ${err}`; });
setInterval(() => refresh().catch(console.error), 30000);
</script>
</body>
</html>
"""


def read_yaml(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    with path.open("r") as handle:
        value = yaml.safe_load(handle) or {}
    return value if isinstance(value, dict) else {}


def ensure_web_permissions(path: Path) -> None:
    """Make generated web files readable by the web server."""
    try:
        if path.is_dir():
            path.chmod(0o755)
        else:
            path.chmod(0o644)
    except OSError:
        pass


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ensure_web_permissions(path.parent)
    with tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False) as handle:
        handle.write(text)
        tmp_name = Path(handle.name)
    os.replace(tmp_name, path)
    ensure_web_permissions(path)


def atomic_write_json(path: Path, data: Any) -> None:
    atomic_write_text(path, json.dumps(data, indent=2, sort_keys=True) + "\n")


def read_submitted_jobs(project_dir: Path) -> list[str]:
    ledger = project_dir / "submitted_jobs.txt"
    if not ledger.is_file():
        return []
    return [line.strip() for line in ledger.read_text().splitlines() if line.strip()]


def discover_events(project_dir: Path) -> list[str]:
    working = project_dir / "working"
    if not working.is_dir():
        return []
    return sorted(path.name for path in working.iterdir() if path.is_dir())


def run_json_command(command: list[str]) -> list[dict[str, Any]]:
    try:
        out = subprocess.run(command, check=True, capture_output=True, text=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        return []
    try:
        decoded = json.loads(out.stdout)
    except json.JSONDecodeError:
        return []
    return [item for item in decoded if isinstance(item, dict)] if isinstance(decoded, list) else []


def condor_q_ad(jobid: str | int | None) -> dict[str, Any] | None:
    if jobid in (None, ""):
        return None
    ads = run_json_command(["condor_q", str(jobid), "-json", "-attributes", CONDOR_ATTRIBUTES])
    return ads[0] if ads else None


def condor_history_ad(jobid: str | int | None) -> dict[str, Any] | None:
    if jobid in (None, ""):
        return None
    ads = run_json_command(["condor_history", str(jobid), "-json", "-limit", "1", "-attributes", CONDOR_ATTRIBUTES])
    return ads[0] if ads else None


def format_runtime(seconds: Any) -> str | None:
    if seconds is None:
        return None
    try:
        seconds = int(seconds)
    except (TypeError, ValueError):
        return None
    hours, remainder = divmod(seconds, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}h {minutes}m {secs}s"
    if minutes:
        return f"{minutes}m {secs}s"
    return f"{secs}s"


def collect_system_info() -> dict[str, Any]:
    cpu_count = os.cpu_count() or 1
    load_avg = os.getloadavg() if hasattr(os, "getloadavg") else (None, None, None)
    info: dict[str, Any] = {
        "hostname": socket.gethostname(), "platform": platform.platform(), "python": sys.version.split()[0],
        "cpu_count_logical": cpu_count, "cpu_count_physical": None, "cpu_freq_mhz_current": None,
        "cpu_freq_mhz_min": None, "cpu_freq_mhz_max": None,
        "load_avg_1m": None if load_avg[0] is None else round(load_avg[0], 3),
        "load_avg_5m": None if load_avg[1] is None else round(load_avg[1], 3),
        "load_avg_15m": None if load_avg[2] is None else round(load_avg[2], 3),
        "load_percent_1m": None if load_avg[0] is None else round(100.0 * load_avg[0] / cpu_count, 1),
        "memory_total_gb": None, "memory_available_gb": None, "memory_used_percent": None,
    }
    if psutil is None:
        return info
    info["cpu_count_logical"] = psutil.cpu_count(logical=True)
    info["cpu_count_physical"] = psutil.cpu_count(logical=False)
    freq = psutil.cpu_freq()
    if freq is not None:
        info["cpu_freq_mhz_current"] = round(freq.current, 1)
        info["cpu_freq_mhz_min"] = round(freq.min, 1)
        info["cpu_freq_mhz_max"] = round(freq.max, 1)
    memory = psutil.virtual_memory()
    info["memory_total_gb"] = round(memory.total / 1024**3, 2)
    info["memory_available_gb"] = round(memory.available / 1024**3, 2)
    info["memory_used_percent"] = memory.percent
    return info


def read_heartbeat(event_dir: Path, heartbeat_filename: str) -> dict[str, Any] | None:
    heartbeat_path = event_dir / heartbeat_filename
    if not heartbeat_path.is_file():
        return None
    try:
        data = json.loads(heartbeat_path.read_text())
    except json.JSONDecodeError:
        return {"error": "invalid heartbeat JSON"}
    if not isinstance(data, dict):
        return {"error": "heartbeat JSON is not an object"}
    try:
        data["age_seconds"] = time.time() - heartbeat_path.stat().st_mtime
    except OSError:
        pass
    return data


def final_result_completed(event_dir: Path) -> bool:
    final_result = event_dir / "pe" / "final_result"
    return final_result.is_dir() and any(path.suffix == ".hdf5" for path in final_result.iterdir())


def job_row_from_ad(ad: dict[str, Any] | None, fallback_status: str) -> dict[str, Any]:
    if ad is None:
        return {"status": fallback_status, "request_cpus": None, "request_memory_mb": None, "remote_host": None, "runtime": None, "disk_usage": None, "rss_kb": None, "note": None}
    return {
        "status": CONDOR_STATUS.get(ad.get("JobStatus"), fallback_status),
        "request_cpus": ad.get("RequestCpus"), "request_memory_mb": ad.get("RequestMemory"),
        "remote_host": ad.get("RemoteHost"), "runtime": format_runtime(ad.get("RemoteWallClockTime")),
        "disk_usage": ad.get("DiskUsage"), "rss_kb": ad.get("ResidentSetSize") or ad.get("ImageSize") or ad.get("MemoryUsage"),
        "note": ad.get("HoldReason"),
    }


def should_publish_output(path: Path, extensions: tuple[str, ...]) -> bool:
    return path.is_file() and path.suffix.lower() in extensions and "checkpoint" not in path.name.lower()


def publish_event_outputs(event_dir: Path, webdir: Path, event: str, extensions: tuple[str, ...], max_files: int) -> list[dict[str, str]]:
    outputs: list[dict[str, str]] = []
    if not event_dir.is_dir() or max_files <= 0:
        return outputs
    candidates = [path for path in event_dir.rglob("*") if should_publish_output(path, extensions)]
    candidates = sorted(candidates, key=lambda p: (p.suffix.lower() not in {".png", ".html", ".pdf"}, str(p)))[:max_files]
    for src in candidates:
        rel = src.relative_to(event_dir)
        dst = webdir / "artifacts" / event / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        ensure_web_permissions(dst.parent)
        try:
            shutil.copy2(src, dst)
            ensure_web_permissions(dst)
        except OSError:
            continue
        outputs.append({"label": str(rel), "href": f"artifacts/{event}/{rel.as_posix()}"})
    return outputs


def collect_jobs(project_dir: Path, include_history: bool = True, heartbeat_filename: str = "heartbeat.json", webdir: Path | None = None, copy_outputs: bool = False, output_extensions: tuple[str, ...] = DEFAULT_OUTPUT_EXTENSIONS, max_artifacts_per_event: int = 40) -> list[dict[str, Any]]:
    submitted = set(read_submitted_jobs(project_dir))
    events = sorted(set(discover_events(project_dir)) | submitted)
    rows: list[dict[str, Any]] = []
    for event in events:
        event_dir = project_dir / "working" / event
        status_info = read_yaml(event_dir / "status.yaml")
        jobid = status_info.get("jobid")
        fallback_status = status_info.get("status") or ("submitted" if event in submitted else "pending")
        ad = condor_q_ad(jobid)
        source = "condor_q" if ad is not None else "local"
        if ad is None and include_history:
            ad = condor_history_ad(jobid)
            if ad is not None:
                source = "condor_history"
        normalized = job_row_from_ad(ad, fallback_status)
        status = normalized["status"]
        note = normalized["note"]
        if ad is None and jobid:
            if final_result_completed(event_dir):
                status = "completed"
                note = "not in condor_q; final result found"
            else:
                note = "not found in condor_q"
        outputs = publish_event_outputs(event_dir, webdir, event, output_extensions, max_artifacts_per_event) if (copy_outputs and webdir is not None) else []
        rows.append({
            "event": event, "status": status, "jobid": jobid, "source": source,
            "request_cpus": normalized["request_cpus"], "request_memory_mb": normalized["request_memory_mb"],
            "remote_host": normalized["remote_host"], "runtime": normalized["runtime"], "disk_usage": normalized["disk_usage"],
            "rss_kb": normalized["rss_kb"], "heartbeat": read_heartbeat(event_dir, heartbeat_filename), "outputs": outputs, "note": note,
        })
    return rows


def build_status(project_dir: Path, include_history: bool = True, heartbeat_filename: str = "heartbeat.json", webdir: Path | None = None, copy_outputs: bool = False, command_file: Path | None = None, output_extensions: tuple[str, ...] = DEFAULT_OUTPUT_EXTENSIONS, max_artifacts_per_event: int = 40) -> dict[str, Any]:
    project_path = project_dir.expanduser().resolve()
    web_path = webdir.expanduser().resolve() if webdir is not None else None
    return {
        "generated_at": time.time(), "project_dir": str(project_path),
        "command_file": None if command_file is None else str(command_file.expanduser().resolve()),
        "system": collect_system_info(),
        "jobs": collect_jobs(project_path, include_history=include_history, heartbeat_filename=heartbeat_filename, webdir=web_path, copy_outputs=copy_outputs, output_extensions=output_extensions, max_artifacts_per_event=max_artifacts_per_event),
    }


def publish_once(project_dir: Path, webdir: Path, include_history: bool = True, heartbeat_filename: str = "heartbeat.json", copy_outputs: bool = False, command_file: Path | None = None, output_extensions: tuple[str, ...] = DEFAULT_OUTPUT_EXTENSIONS, max_artifacts_per_event: int = 40) -> dict[str, Any]:
    webdir = webdir.expanduser().resolve()
    webdir.mkdir(parents=True, exist_ok=True)
    ensure_web_permissions(webdir)
    payload = build_status(project_dir, include_history=include_history, heartbeat_filename=heartbeat_filename, webdir=webdir, copy_outputs=copy_outputs, command_file=command_file, output_extensions=output_extensions, max_artifacts_per_event=max_artifacts_per_event)
    atomic_write_json(webdir / "status.json", payload)
    atomic_write_text(webdir / "index.html", INDEX_HTML)
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Publish a static Purohit monitor into a webdir.")
    parser.add_argument("--project-dir", required=True, type=Path, help="Project directory containing submitted_jobs.txt and working/.")
    parser.add_argument("--webdir", required=True, type=Path, help="Output directory served by existing webdir/PESummary infrastructure.")
    parser.add_argument("--interval", type=int, default=300, help="Refresh interval in seconds when running continuously.")
    parser.add_argument("--once", action="store_true", help="Publish once and exit.")
    parser.add_argument("--no-history", action="store_true", help="Do not query condor_history when condor_q has no live job.")
    parser.add_argument("--heartbeat-filename", default="heartbeat.json", help="Per-event heartbeat JSON filename relative to project_dir/working/<event>/.")
    parser.add_argument("--copy-to", type=Path, default=None, help="Optional extra directory to mirror the generated static monitor files into.")
    parser.add_argument("--copy-outputs", action="store_true", help="Copy selected event output files/plots into the static webdir artifacts tree.")
    parser.add_argument("--command-file", type=Path, default=None, help="Command JSON file read by the manager, shown for convenience in status.json.")
    parser.add_argument("--output-extensions", default=",".join(DEFAULT_OUTPUT_EXTENSIONS), help="Comma-separated extensions to expose as output artifacts.")
    parser.add_argument("--max-artifacts-per-event", type=int, default=40, help="Maximum number of artifacts copied per event.")
    return parser.parse_args()


def mirror_webdir(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    ensure_web_permissions(destination)
    for name in ("index.html", "status.json"):
        shutil.copy2(source / name, destination / name)
        ensure_web_permissions(destination / name)


def parse_extensions(raw: str) -> tuple[str, ...]:
    exts = []
    for item in raw.split(","):
        item = item.strip().lower()
        if not item:
            continue
        exts.append(item if item.startswith(".") else f".{item}")
    return tuple(exts) or DEFAULT_OUTPUT_EXTENSIONS


def main() -> None:
    args = parse_args()
    include_history = not args.no_history
    output_extensions = parse_extensions(args.output_extensions)
    while True:
        payload = publish_once(
            args.project_dir, args.webdir, include_history=include_history, heartbeat_filename=args.heartbeat_filename,
            copy_outputs=args.copy_outputs, command_file=args.command_file, output_extensions=output_extensions,
            max_artifacts_per_event=args.max_artifacts_per_event,
        )
        if args.copy_to is not None:
            mirror_webdir(args.webdir.expanduser().resolve(), args.copy_to.expanduser().resolve())
        print(f"Published {len(payload['jobs'])} jobs to {args.webdir} at {time.strftime('%Y-%m-%d %H:%M:%S')}")
        if args.once:
            return
        time.sleep(args.interval)


if __name__ == "__main__":
    main()
