"""Static webdir monitor publisher for Purohit rerun projects."""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import platform
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from typing import Any

import yaml

try:
    import psutil
except ImportError:  # pragma: no cover - optional dependency
    psutil = None


CONDOR_STATUS = {1: "idle", 2: "running", 3: "completed", 4: "removed", 5: "held", 6: "suspended"}
CONDOR_RESOURCE_ATTRIBUTES = [
    "DiskUsage",
    "ImageSize",
    "ResidentSetSize",
    "MemoryUsage",
    "ProportionalSetSizeKb",
    "RemoteUserCpu",
    "RemoteSysCpu",
    "CumulativeRemoteUserCpu",
    "CumulativeRemoteSysCpu",
    "CpusUsage",
    "CommittedTime",
]
CONDOR_ATTRIBUTES = ",".join([
    "ClusterId", "ProcId", "JobStatus", "RequestCpus", "RequestMemory", "RemoteHost",
    "RemoteWallClockTime", "JobCurrentStartDate", "EnteredCurrentStatus", "HoldReason",
    *CONDOR_RESOURCE_ATTRIBUTES,
])
DAG_ATTRIBUTES = ",".join([
    "ClusterId", "ProcId", "JobStatus", "Owner", "BatchName", "DAGManJobId", "DAGParentNodeNames",
    "DAGNodeName", "RequestCpus", "RequestMemory", "RemoteHost", "RemoteWallClockTime",
    "JobCurrentStartDate", "EnteredCurrentStatus", "HoldReason", "Iwd", "Cmd", "Args", "Out", "Err", "Log",
    *CONDOR_RESOURCE_ATTRIBUTES,
])
DEFAULT_OUTPUT_EXTENSIONS = (".png", ".jpg", ".jpeg", ".svg", ".pdf", ".html", ".txt", ".log", ".out", ".err", ".hdf5", ".json")

INDEX_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Purohit static job manager</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif; margin: 2rem; line-height: 1.35; }
    h1, h2 { margin-bottom: 0.4rem; }
    nav a { margin-right: 1rem; }
    .muted { opacity: 0.72; }
    .card { border: 1px solid rgba(128,128,128,0.25); border-radius: 12px; padding: 1rem; margin: 1rem 0; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; }
    th, td { text-align: left; border-bottom: 1px solid rgba(128,128,128,0.25); padding: 0.55rem; font-size: 0.9rem; vertical-align: top; }
    th { position: sticky; top: 0; background: Canvas; }
    code, pre { padding: 0.1rem 0.25rem; border-radius: 4px; background: rgba(128,128,128,0.15); }
    pre { white-space: pre-wrap; padding: 0.75rem; overflow-x: auto; }
    a { text-decoration: none; }
    .status-running { color: #047857; font-weight: 700; }
    .status-completed { color: #2563eb; font-weight: 700; }
    .status-held, .status-removed, .status-failed { color: #b91c1c; font-weight: 700; }
    .status-idle, .status-submitted, .status-pending { color: #92400e; font-weight: 700; }
    .small { font-size: 0.82rem; }
  </style>
</head>
<body>
  <h1>Purohit static job manager</h1>
  <nav><a href="index.html">Monitor</a><a href="tunnel.html">Commands</a><a href="files.html">Files</a><a href="health.html">Health</a></nav>
  <p class="muted">PESummary-style static view generated by a background publisher/manager. This page reads static JSON only.</p>

  <div class="card">
    <div><strong>Project:</strong> <code id="project-dir">loading...</code></div>
    <div><strong>Generated:</strong> <span id="generated">loading...</span></div>
    <div><strong>Publisher host:</strong> <span id="publisher-host">loading...</span></div>
    <div><strong>Command file:</strong> <code id="command-file">not configured</code></div>
  </div>

  <h2>Publisher host resources</h2>
  <div id="system" class="grid"></div>

  <h2>Jobs</h2>
  <div class="card">
    <table>
      <thead>
        <tr>
          <th>Event</th><th>Status</th><th>DAG Cluster ID</th><th>CPUs</th><th>Memory MB</th>
          <th>Remote host / node</th><th>Runtime</th><th>Disk / RSS</th><th>Outputs</th><th>Heartbeat</th><th>Notes</th>
        </tr>
      </thead>
      <tbody id="jobs"></tbody>
    </table>
  </div>

  <h2>Command queue</h2>
  <div class="card">
    <p class="muted small">Static pages cannot write to the submit host by themselves. To manage jobs, write commands into the manager command JSON file on the submit host, or use <code>scripts/write_manager_command.py</code>.</p>
    <pre id="command-example">loading...</pre>
  </div>

<script>
function fmt(value) { return value === null || value === undefined || value === "" ? "—" : value; }
function card(label, value) { return `<div class="card"><div class="muted small">${label}</div><div><strong>${fmt(value)}</strong></div></div>`; }
function statusClass(status) { return `status-${String(status || "unknown").toLowerCase()}`; }
function heartbeatText(hb) {
  if (!hb) return "—";
  const bits = [];
  if (hb.hostname) bits.push(hb.hostname);
  if (hb.load_avg_1m !== undefined && hb.load_avg_1m !== null) bits.push(`load1=${hb.load_avg_1m}`);
  if (hb.memory_available_gb !== undefined && hb.memory_available_gb !== null) bits.push(`mem_avail=${hb.memory_available_gb} GB`);
  if (hb.age_seconds !== undefined && hb.age_seconds !== null) bits.push(`age=${Math.round(hb.age_seconds)}s`);
  return bits.join("; ") || "—";
}
function detailsLink(job) {
  const href = job.event_page || `dag.html?event=${encodeURIComponent(String(job.event || ""))}`;
  return `<a href="${href}">${fmt(job.event)}</a>`;
}
function outputsSummary(job) {
  const count = (job.outputs || []).length;
  const href = job.event_page || `dag.html?event=${encodeURIComponent(String(job.event || ""))}`;
  return `<a href="${href}">${count} file${count === 1 ? "" : "s"}</a>`;
}
function commandExample(event) { return JSON.stringify({commands: [{action: "submit_event", event: event || "S240000a"}, {action: "hold_event", event: event || "S240000a"}, {action: "release_event", event: event || "S240000a"}]}, null, 2); }
async function refresh() {
  const response = await fetch(`status.json?ts=${Date.now()}`, {cache: "no-store"});
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const data = await response.json();
  document.getElementById("project-dir").textContent = data.project_dir;
  document.getElementById("generated").textContent = new Date(data.generated_at * 1000).toLocaleString();
  document.getElementById("publisher-host").textContent = data.system.hostname || "—";
  document.getElementById("command-file").textContent = data.command_file || "not configured";
  const s = data.system || {};
  document.getElementById("system").innerHTML = [card("Host", s.hostname), card("Platform", s.platform), card("Logical CPUs", s.cpu_count_logical), card("Physical CPUs", s.cpu_count_physical), card("CPU frequency MHz", s.cpu_freq_mhz_current), card("Load average 1m", s.load_avg_1m), card("Load %", s.load_percent_1m), card("Memory used %", s.memory_used_percent)].join("");
  const rows = (data.jobs || []).map(job => `<tr>
      <td>${detailsLink(job)}</td><td class="${statusClass(job.status)}">${fmt(job.status)}</td><td>${fmt(job.jobid)}</td>
      <td>${fmt(job.request_cpus)}</td><td>${fmt(job.request_memory_mb)}</td><td>${fmt(job.remote_host)}</td>
      <td>${fmt(job.runtime)}</td><td>${fmt(job.disk_usage)} / ${fmt(job.rss_kb)}</td><td>${outputsSummary(job)}</td>
      <td class="small">${heartbeatText(job.heartbeat)}</td><td class="small">${fmt(job.note)}</td>
    </tr>`).join("");
  document.getElementById("jobs").innerHTML = rows || `<tr><td colspan="11">No jobs found.</td></tr>`;
  document.getElementById("command-example").textContent = commandExample((data.jobs || [])[0]?.event);
}
refresh().catch(err => { document.getElementById("generated").textContent = `error: ${err}`; });
setInterval(() => refresh().catch(console.error), 30000);
</script>
</body>
</html>
"""


def event_detail_html(event: str) -> str:
    event_json = json.dumps(event)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Purohit event detail: {event}</title>
  <style>
    :root {{ color-scheme: light dark; }}
    body {{ font-family: system-ui, -apple-system, BlinkMacSystemFont, sans-serif; margin: 2rem; line-height: 1.35; }}
    nav a {{ margin-right: 1rem; }}
    .card {{ border: 1px solid rgba(128,128,128,0.25); border-radius: 12px; padding: 1rem; margin: 1rem 0; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 0.5rem; }}
    th, td {{ text-align: left; border-bottom: 1px solid rgba(128,128,128,0.25); padding: 0.45rem; font-size: 0.9rem; vertical-align: top; }}
    code, pre {{ padding: 0.1rem 0.25rem; border-radius: 4px; background: rgba(128,128,128,0.15); }}
    pre {{ padding: 0.75rem; white-space: pre-wrap; overflow-x: auto; max-height: 40rem; }}
    .muted {{ opacity: 0.72; }}
    .status-running {{ color: #047857; font-weight: 700; }}
    .status-completed {{ color: #2563eb; font-weight: 700; }}
    .status-held, .status-removed, .status-failed {{ color: #b91c1c; font-weight: 700; }}
    .status-idle, .status-submitted, .status-pending {{ color: #92400e; font-weight: 700; }}
  </style>
</head>
<body>
  <h1 id="title">Purohit event detail</h1>
  <nav><a href="../../index.html">Monitor</a><a href="../../tunnel.html">Commands</a><a href="../../files.html">Files</a><a href="../../health.html">Health</a></nav>
  <p class="muted">Per-event detail page generated into <code>events/{event}/</code>.</p>
  <div id="summary" class="card">Loading...</div>
  <h2>Outputs and logs</h2><div id="outputs" class="card"></div>
  <h2>Condor DAG jobs</h2><div id="jobs" class="card"></div>
  <h2>Raw detail JSON</h2><div class="card"><pre id="raw">loading...</pre></div>
<script>
const EVENT = {event_json};
function fmt(x) {{ return x === null || x === undefined || x === "" ? "—" : x; }}
function esc(x) {{ return String(x ?? "").replace(/[&<>]/g, c => ({{"&":"&amp;","<":"&lt;",">":"&gt;"}}[c])); }}
function statusClass(status) {{ return `status-${{String(status || "unknown").toLowerCase()}}`; }}
function row(label, value) {{ return `<tr><th>${{esc(label)}}</th><td>${{esc(fmt(value))}}</td></tr>`; }}
function table(rows) {{ return `<table><tbody>${{rows.join("")}}</tbody></table>`; }}
function outputTable(outputs) {{
  if (!outputs || outputs.length === 0) return "No copied output products/logs found yet.";
  return `<table><thead><tr><th>Product / log</th></tr></thead><tbody>${{outputs.map(item => `<tr><td><a href="../../${{item.href}}">${{esc(item.label)}}</a></td></tr>`).join("")}}</tbody></table>`;
}}
function jobTable(jobs) {{
  if (!jobs || jobs.length === 0) return "No DAG subjobs found in condor_q/condor_history.";
  return `<table><thead><tr><th>Job ID</th><th>Status</th><th>Node</th><th>Remote host</th><th>Wall time</th><th>CPU time</th><th>CPU eff.</th><th>Req. CPUs</th><th>Req. mem MB</th><th>Mem MB</th><th>RSS MB</th><th>Disk MB</th><th>Hold reason</th><th>Logs</th></tr></thead><tbody>${{jobs.map(j => `<tr><td>${{esc(j.job_id)}}</td><td class="${{statusClass(j.status)}}">${{esc(fmt(j.status))}}</td><td>${{esc(fmt(j.node))}}</td><td>${{esc(fmt(j.remote_host))}}</td><td>${{esc(fmt(j.runtime))}}</td><td>${{esc(fmt(j.cpu_time))}}</td><td>${{esc(fmt(j.cpu_efficiency_percent))}}</td><td>${{esc(fmt(j.request_cpus))}}</td><td>${{esc(fmt(j.request_memory_mb))}}</td><td>${{esc(fmt(j.memory_usage_mb))}}</td><td>${{esc(fmt(j.rss_mb))}}</td><td>${{esc(fmt(j.disk_usage_mb))}}</td><td>${{esc(fmt(j.hold_reason))}}</td><td><div>out: <code>${{esc(fmt(j.out))}}</code></div><div>err: <code>${{esc(fmt(j.err))}}</code></div><div>log: <code>${{esc(fmt(j.log))}}</code></div></td></tr>`).join("")}}</tbody></table>`;
}}
async function refresh() {{
  document.getElementById("title").textContent = `Purohit event detail: ${{EVENT}}`;
  const [statusResp, detailResp] = await Promise.all([fetch(`../../status.json?ts=${{Date.now()}}`, {{cache: "no-store"}}), fetch(`../../dag_details.json?ts=${{Date.now()}}`, {{cache: "no-store"}})]);
  const status = await statusResp.json();
  const details = await detailResp.json();
  const job = (status.jobs || []).find(j => j.event === EVENT) || {{}};
  const detail = (details.events || {{}})[EVENT] || {{}};
  document.getElementById("summary").innerHTML = table([row("event", EVENT), row("status", job.status), row("DAG cluster id", job.jobid || detail.dag_cluster_id), row("source", job.source), row("runtime", job.runtime), row("remote host", job.remote_host), row("requested CPUs", job.request_cpus), row("requested memory MB", job.request_memory_mb), row("disk / RSS", `${{fmt(job.disk_usage)}} / ${{fmt(job.rss_kb)}}`), row("detail generated", detail.generated_at ? new Date(detail.generated_at * 1000).toLocaleString() : null), row("live child jobs", detail.live_jobs_count), row("history child jobs", detail.history_jobs_count), row("note", job.note || detail.note)]);
  document.getElementById("outputs").innerHTML = outputTable(job.outputs || []);
  document.getElementById("jobs").innerHTML = jobTable(detail.jobs || []);
  document.getElementById("raw").textContent = JSON.stringify({{job, dag: detail}}, null, 2);
}}
refresh().catch(err => {{ document.getElementById("summary").textContent = `error: ${{err}}`; }});
setInterval(() => refresh().catch(console.error), 30000);
</script>
</body>
</html>
"""


DAG_HTML = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Purohit DAG detail</title>
</head>
<body>
  <p>This compatibility page has been superseded by per-event pages. Open the event from <a href="index.html">the monitor</a>.</p>
</body>
</html>
"""


def read_yaml(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    with path.open("r") as handle:
        value = yaml.safe_load(handle) or {}
    return value if isinstance(value, dict) else {}


def ensure_web_permissions(path: Path) -> None:
    try:
        if path.is_dir():
            path.chmod(0o755)
        else:
            path.chmod(0o644)
    except OSError:
        pass


def safe_event_dir(event: Any) -> str:
    name = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(event or "unknown")).strip("._")
    return name or "unknown"


def event_page_href(event: Any) -> str:
    return f"events/{safe_event_dir(event)}/index.html"


def _clean_json(value: Any) -> Any:
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None
    if isinstance(value, dict):
        return {str(k): _clean_json(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_clean_json(v) for v in value]
    return value


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ensure_web_permissions(path.parent)
    with tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False) as handle:
        handle.write(text)
        tmp_name = Path(handle.name)
    os.replace(tmp_name, path)
    ensure_web_permissions(path)


def atomic_write_json(path: Path, data: Any) -> None:
    atomic_write_text(path, json.dumps(_clean_json(data), indent=2, sort_keys=True, allow_nan=False) + "\n")


def read_submitted_jobs(project_dir: Path) -> list[str]:
    ledger = project_dir / "submitted_jobs.txt"
    if not ledger.is_file():
        return []
    return [line.strip() for line in ledger.read_text().splitlines() if line.strip()]


def discover_events(project_dir: Path) -> list[str]:
    working = project_dir / "working"
    if not working.is_dir():
        return []
    return sorted(path.name for path in working.iterdir() if path.is_dir())


def run_json_command(command: list[str]) -> list[dict[str, Any]]:
    try:
        out = subprocess.run(command, check=True, capture_output=True, text=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        return []
    try:
        decoded = json.loads(out.stdout)
    except json.JSONDecodeError:
        return []
    return [item for item in decoded if isinstance(item, dict)] if isinstance(decoded, list) else []


def condor_q_ad(jobid: str | int | None) -> dict[str, Any] | None:
    if jobid in (None, ""):
        return None
    ads = run_json_command(["condor_q", str(jobid), "-json", "-attributes", CONDOR_ATTRIBUTES])
    return ads[0] if ads else None


def condor_history_ad(jobid: str | int | None) -> dict[str, Any] | None:
    if jobid in (None, ""):
        return None
    ads = run_json_command(["condor_history", str(jobid), "-json", "-limit", "1", "-attributes", CONDOR_ATTRIBUTES])
    return ads[0] if ads else None


def cluster_id(jobid: Any) -> int | None:
    if jobid in (None, ""):
        return None
    match = re.match(r"^(\d+)(?:\.\d+)?$", str(jobid).strip())
    return int(match.group(1)) if match else None


def condor_dag_ads(dag_cluster: int | None, *, include_history: bool = True) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    if dag_cluster is None:
        return [], []
    constraint = f"(ClusterId == {dag_cluster}) || (DAGManJobId == {dag_cluster})"
    live = run_json_command(["condor_q", "-constraint", constraint, "-json", "-attributes", DAG_ATTRIBUTES])
    history: list[dict[str, Any]] = []
    if include_history:
        history = run_json_command(["condor_history", "-constraint", constraint, "-json", "-limit", "200", "-attributes", DAG_ATTRIBUTES])
    return live, history


def as_float(value: Any) -> float | None:
    if value in (None, ""):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def round_or_none(value: Any, digits: int = 2) -> float | None:
    number = as_float(value)
    return None if number is None else round(number, digits)


def kb_to_mb(value: Any) -> float | None:
    number = as_float(value)
    return None if number is None else round(number / 1024.0, 2)


def format_runtime(seconds: Any) -> str | None:
    if seconds is None:
        return None
    try:
        seconds = int(seconds)
    except (TypeError, ValueError):
        return None
    hours, remainder = divmod(seconds, 3600)
    minutes, secs = divmod(remainder, 60)
    if hours:
        return f"{hours}h {minutes}m {secs}s"
    if minutes:
        return f"{minutes}m {secs}s"
    return f"{secs}s"


def collect_system_info() -> dict[str, Any]:
    cpu_count = os.cpu_count() or 1
    load_avg = os.getloadavg() if hasattr(os, "getloadavg") else (None, None, None)
    info: dict[str, Any] = {"hostname": socket.gethostname(), "platform": platform.platform(), "python": sys.version.split()[0], "cpu_count_logical": cpu_count, "cpu_count_physical": None, "cpu_freq_mhz_current": None, "cpu_freq_mhz_min": None, "cpu_freq_mhz_max": None, "load_avg_1m": None if load_avg[0] is None else round(load_avg[0], 3), "load_avg_5m": None if load_avg[1] is None else round(load_avg[1], 3), "load_avg_15m": None if load_avg[2] is None else round(load_avg[2], 3), "load_percent_1m": None if load_avg[0] is None else round(100.0 * load_avg[0] / cpu_count, 1), "memory_total_gb": None, "memory_available_gb": None, "memory_used_percent": None}
    if psutil is None:
        return info
    info["cpu_count_logical"] = psutil.cpu_count(logical=True)
    info["cpu_count_physical"] = psutil.cpu_count(logical=False)
    freq = psutil.cpu_freq()
    if freq is not None:
        info["cpu_freq_mhz_current"] = round(freq.current, 1)
        info["cpu_freq_mhz_min"] = round(freq.min, 1)
        info["cpu_freq_mhz_max"] = round(freq.max, 1)
    memory = psutil.virtual_memory()
    info["memory_total_gb"] = round(memory.total / 1024**3, 2)
    info["memory_available_gb"] = round(memory.available / 1024**3, 2)
    info["memory_used_percent"] = memory.percent
    return info


def read_heartbeat(event_dir: Path, heartbeat_filename: str) -> dict[str, Any] | None:
    heartbeat_path = event_dir / heartbeat_filename
    if not heartbeat_path.is_file():
        return None
    try:
        data = json.loads(heartbeat_path.read_text())
    except json.JSONDecodeError:
        return {"error": "invalid heartbeat JSON"}
    if not isinstance(data, dict):
        return {"error": "heartbeat JSON is not an object"}
    try:
        data["age_seconds"] = time.time() - heartbeat_path.stat().st_mtime
    except OSError:
        pass
    return data


def final_result_completed(event_dir: Path) -> bool:
    final_result = event_dir / "pe" / "final_result"
    return final_result.is_dir() and any(path.suffix == ".hdf5" for path in final_result.iterdir())


def cpu_seconds_from_ad(ad: dict[str, Any]) -> float | None:
    user = as_float(ad.get("RemoteUserCpu"))
    sys_cpu = as_float(ad.get("RemoteSysCpu"))
    cumulative_user = as_float(ad.get("CumulativeRemoteUserCpu"))
    cumulative_sys = as_float(ad.get("CumulativeRemoteSysCpu"))
    total = None
    if user is not None or sys_cpu is not None:
        total = (user or 0.0) + (sys_cpu or 0.0)
    if total is None and (cumulative_user is not None or cumulative_sys is not None):
        total = (cumulative_user or 0.0) + (cumulative_sys or 0.0)
    return total


def resource_usage_from_ad(ad: dict[str, Any] | None) -> dict[str, Any]:
    if ad is None:
        return {
            "memory_usage_mb": None,
            "rss_mb": None,
            "image_size_mb": None,
            "disk_usage_mb": None,
            "remote_user_cpu_s": None,
            "remote_sys_cpu_s": None,
            "cpu_time_s": None,
            "cpu_time": None,
            "cpu_efficiency_percent": None,
            "cpus_usage": None,
        }
    wall = as_float(ad.get("RemoteWallClockTime"))
    cpu_time = cpu_seconds_from_ad(ad)
    efficiency = None
    if wall and wall > 0 and cpu_time is not None:
        efficiency = round(100.0 * cpu_time / wall, 1)
    return {
        "memory_usage_mb": round_or_none(ad.get("MemoryUsage")),
        "rss_mb": kb_to_mb(ad.get("ResidentSetSize")),
        "image_size_mb": kb_to_mb(ad.get("ImageSize")),
        "proportional_set_size_mb": kb_to_mb(ad.get("ProportionalSetSizeKb")),
        "disk_usage_mb": kb_to_mb(ad.get("DiskUsage")),
        "remote_user_cpu_s": round_or_none(ad.get("RemoteUserCpu")),
        "remote_sys_cpu_s": round_or_none(ad.get("RemoteSysCpu")),
        "cumulative_remote_user_cpu_s": round_or_none(ad.get("CumulativeRemoteUserCpu")),
        "cumulative_remote_sys_cpu_s": round_or_none(ad.get("CumulativeRemoteSysCpu")),
        "cpu_time_s": None if cpu_time is None else round(cpu_time, 2),
        "cpu_time": format_runtime(cpu_time),
        "cpu_efficiency_percent": efficiency,
        "cpus_usage": round_or_none(ad.get("CpusUsage")),
        "committed_time": format_runtime(ad.get("CommittedTime")),
    }


def job_row_from_ad(ad: dict[str, Any] | None, fallback_status: str) -> dict[str, Any]:
    resources = resource_usage_from_ad(ad)
    if ad is None:
        return {"status": fallback_status, "request_cpus": None, "request_memory_mb": None, "remote_host": None, "runtime": None, "disk_usage": None, "rss_kb": None, "note": None, **resources}
    return {"status": CONDOR_STATUS.get(ad.get("JobStatus"), fallback_status), "request_cpus": ad.get("RequestCpus"), "request_memory_mb": ad.get("RequestMemory"), "remote_host": ad.get("RemoteHost"), "runtime": format_runtime(ad.get("RemoteWallClockTime")), "disk_usage": ad.get("DiskUsage"), "rss_kb": ad.get("ResidentSetSize") or ad.get("ImageSize") or ad.get("MemoryUsage"), "note": ad.get("HoldReason"), **resources}


def dag_row_from_ad(ad: dict[str, Any], source: str) -> dict[str, Any]:
    cluster = ad.get("ClusterId")
    proc = ad.get("ProcId", 0)
    resources = resource_usage_from_ad(ad)
    return {"job_id": None if cluster is None else f"{cluster}.{proc}", "cluster_id": cluster, "proc_id": proc, "status": CONDOR_STATUS.get(ad.get("JobStatus"), ad.get("JobStatus")), "source": source, "owner": ad.get("Owner"), "batch_name": ad.get("BatchName"), "dagman_job_id": ad.get("DAGManJobId"), "node": ad.get("DAGNodeName") or ad.get("DAGParentNodeNames"), "request_cpus": ad.get("RequestCpus"), "request_memory_mb": ad.get("RequestMemory"), "remote_host": ad.get("RemoteHost"), "runtime": format_runtime(ad.get("RemoteWallClockTime")), "hold_reason": ad.get("HoldReason"), "disk_usage": ad.get("DiskUsage"), "rss_kb": ad.get("ResidentSetSize") or ad.get("ImageSize") or ad.get("MemoryUsage"), "iwd": ad.get("Iwd"), "cmd": ad.get("Cmd"), "args": ad.get("Args"), "out": ad.get("Out"), "err": ad.get("Err"), "log": ad.get("Log"), **resources}


def should_publish_output(path: Path, extensions: tuple[str, ...]) -> bool:
    return path.is_file() and path.suffix.lower() in extensions and "checkpoint" not in path.name.lower()


def publish_event_outputs(event_dir: Path, webdir: Path, event: str, extensions: tuple[str, ...], max_files: int) -> list[dict[str, str]]:
    outputs: list[dict[str, str]] = []
    if not event_dir.is_dir() or max_files <= 0:
        return outputs
    candidates = [path for path in event_dir.rglob("*") if should_publish_output(path, extensions)]
    candidates = sorted(candidates, key=lambda p: (p.suffix.lower() not in {".png", ".html", ".pdf"}, str(p)))[:max_files]
    for src in candidates:
        rel = src.relative_to(event_dir)
        dst = webdir / "artifacts" / event / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        ensure_web_permissions(dst.parent)
        try:
            shutil.copy2(src, dst)
            ensure_web_permissions(dst)
        except OSError:
            continue
        outputs.append({"label": str(rel), "href": f"artifacts/{event}/{rel.as_posix()}"})
    return outputs


def collect_jobs(project_dir: Path, include_history: bool = True, heartbeat_filename: str = "heartbeat.json", webdir: Path | None = None, copy_outputs: bool = False, output_extensions: tuple[str, ...] = DEFAULT_OUTPUT_EXTENSIONS, max_artifacts_per_event: int = 40) -> list[dict[str, Any]]:
    submitted = set(read_submitted_jobs(project_dir))
    events = sorted(set(discover_events(project_dir)) | submitted)
    rows: list[dict[str, Any]] = []
    for event in events:
        event_dir = project_dir / "working" / event
        status_info = read_yaml(event_dir / "status.yaml")
        jobid = status_info.get("jobid")
        fallback_status = status_info.get("status") or ("submitted" if event in submitted else "pending")
        ad = condor_q_ad(jobid)
        source = "condor_q" if ad is not None else "local"
        if ad is None and include_history:
            ad = condor_history_ad(jobid)
            if ad is not None:
                source = "condor_history"
        normalized = job_row_from_ad(ad, fallback_status)
        status = normalized["status"]
        note = normalized["note"]
        if ad is None and jobid:
            if final_result_completed(event_dir):
                status = "completed"
                note = "not in condor_q; final result found"
            else:
                note = "not found in condor_q"
        outputs = publish_event_outputs(event_dir, webdir, event, output_extensions, max_artifacts_per_event) if (copy_outputs and webdir is not None) else []
        rows.append({"event": event, "event_page": event_page_href(event), "status": status, "jobid": jobid, "source": source, "request_cpus": normalized["request_cpus"], "request_memory_mb": normalized["request_memory_mb"], "remote_host": normalized["remote_host"], "runtime": normalized["runtime"], "disk_usage": normalized["disk_usage"], "rss_kb": normalized["rss_kb"], "memory_usage_mb": normalized.get("memory_usage_mb"), "rss_mb": normalized.get("rss_mb"), "disk_usage_mb": normalized.get("disk_usage_mb"), "cpu_time": normalized.get("cpu_time"), "cpu_efficiency_percent": normalized.get("cpu_efficiency_percent"), "heartbeat": read_heartbeat(event_dir, heartbeat_filename), "outputs": outputs, "output_count": len(outputs), "note": note})
    return rows


def collect_dag_details(jobs: list[dict[str, Any]], include_history: bool = True) -> dict[str, Any]:
    events: dict[str, Any] = {}
    for job in jobs:
        event = job.get("event")
        dag_cluster = cluster_id(job.get("jobid"))
        live, history = condor_dag_ads(dag_cluster, include_history=include_history)
        seen: set[tuple[Any, Any]] = set()
        rows: list[dict[str, Any]] = []
        for source, ads in (("condor_q", live), ("condor_history", history)):
            for ad in ads:
                key = (ad.get("ClusterId"), ad.get("ProcId", 0))
                if key in seen:
                    continue
                seen.add(key)
                rows.append(dag_row_from_ad(ad, source))
        events[str(event)] = {"event": event, "dag_cluster_id": dag_cluster, "generated_at": time.time(), "jobs": rows, "live_jobs_count": len(live), "history_jobs_count": len(history), "note": None if dag_cluster is not None else "no DAG cluster id recorded for event"}
    return {"generated_at": time.time(), "events": events}


def build_status(project_dir: Path, include_history: bool = True, heartbeat_filename: str = "heartbeat.json", webdir: Path | None = None, copy_outputs: bool = False, command_file: Path | None = None, output_extensions: tuple[str, ...] = DEFAULT_OUTPUT_EXTENSIONS, max_artifacts_per_event: int = 40) -> dict[str, Any]:
    project_path = project_dir.expanduser().resolve()
    web_path = webdir.expanduser().resolve() if webdir is not None else None
    jobs = collect_jobs(project_path, include_history=include_history, heartbeat_filename=heartbeat_filename, webdir=web_path, copy_outputs=copy_outputs, output_extensions=output_extensions, max_artifacts_per_event=max_artifacts_per_event)
    return {"generated_at": time.time(), "project_dir": str(project_path), "command_file": None if command_file is None else str(command_file.expanduser().resolve()), "system": collect_system_info(), "jobs": jobs}


def publish_event_pages(webdir: Path, jobs: list[dict[str, Any]]) -> None:
    events_dir = webdir / "events"
    events_dir.mkdir(parents=True, exist_ok=True)
    ensure_web_permissions(events_dir)
    for job in jobs:
        event = str(job.get("event") or "unknown")
        atomic_write_text(webdir / event_page_href(event), event_detail_html(event))


def publish_once(project_dir: Path, webdir: Path, include_history: bool = True, heartbeat_filename: str = "heartbeat.json", copy_outputs: bool = False, command_file: Path | None = None, output_extensions: tuple[str, ...] = DEFAULT_OUTPUT_EXTENSIONS, max_artifacts_per_event: int = 40) -> dict[str, Any]:
    webdir = webdir.expanduser().resolve()
    webdir.mkdir(parents=True, exist_ok=True)
    ensure_web_permissions(webdir)
    payload = build_status(project_dir, include_history=include_history, heartbeat_filename=heartbeat_filename, webdir=webdir, copy_outputs=copy_outputs, command_file=command_file, output_extensions=output_extensions, max_artifacts_per_event=max_artifacts_per_event)
    atomic_write_json(webdir / "status.json", payload)
    atomic_write_json(webdir / "dag_details.json", collect_dag_details(payload.get("jobs", []), include_history=include_history))
    atomic_write_text(webdir / "index.html", INDEX_HTML)
    atomic_write_text(webdir / "dag.html", DAG_HTML)
    publish_event_pages(webdir, payload.get("jobs", []))
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Publish a static Purohit monitor into a webdir.")
    parser.add_argument("--project-dir", required=True, type=Path)
    parser.add_argument("--webdir", required=True, type=Path)
    parser.add_argument("--interval", type=int, default=300)
    parser.add_argument("--once", action="store_true")
    parser.add_argument("--no-history", action="store_true")
    parser.add_argument("--heartbeat-filename", default="heartbeat.json")
    parser.add_argument("--copy-to", type=Path, default=None)
    parser.add_argument("--copy-outputs", action="store_true")
    parser.add_argument("--command-file", type=Path, default=None)
    parser.add_argument("--output-extensions", default=",".join(DEFAULT_OUTPUT_EXTENSIONS))
    parser.add_argument("--max-artifacts-per-event", type=int, default=40)
    return parser.parse_args()


def mirror_webdir(source: Path, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    ensure_web_permissions(destination)
    for name in ("index.html", "status.json", "dag.html", "dag_details.json", "tunnel.html", "files.html", "health.html", "health.json", "command_results.json"):
        if (source / name).is_file():
            shutil.copy2(source / name, destination / name)
            ensure_web_permissions(destination / name)
    for dirname in ("events", "artifacts"):
        src = source / dirname
        if src.is_dir():
            dst = destination / dirname
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
            for path in dst.rglob("*"):
                ensure_web_permissions(path)


def parse_extensions(raw: str) -> tuple[str, ...]:
    exts = []
    for item in raw.split(","):
        item = item.strip().lower()
        if item:
            exts.append(item if item.startswith(".") else f".{item}")
    return tuple(exts) or DEFAULT_OUTPUT_EXTENSIONS


def main() -> None:
    args = parse_args()
    include_history = not args.no_history
    output_extensions = parse_extensions(args.output_extensions)
    while True:
        payload = publish_once(args.project_dir, args.webdir, include_history=include_history, heartbeat_filename=args.heartbeat_filename, copy_outputs=args.copy_outputs, command_file=args.command_file, output_extensions=output_extensions, max_artifacts_per_event=args.max_artifacts_per_event)
        if args.copy_to is not None:
            mirror_webdir(args.webdir.expanduser().resolve(), args.copy_to.expanduser().resolve())
        print(f"Published {len(payload['jobs'])} jobs to {args.webdir} at {time.strftime('%Y-%m-%d %H:%M:%S')}")
        if args.once:
            return
        time.sleep(args.interval)


if __name__ == "__main__":
    main()
