name: pur
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - pip
  - pycbc
  - lalsuite
  - ligo-common
  - termcolor
  - pyseobnr
  - htcondor
  - sympy
  - bilby
  - bilby_pipe
